## Aries Protocol Test Suite Sample Configuration ##

[config]
host = "localhost"
port = 3000
endpoint = "http://localhost:3000"

tests = [
    "connections*",
]

[config.subject]
endpoint="http://localhost:3001"
