## Aries Protocol Test Suite Sample Configuration ##

[config]
host = "localhost"
port = 3000
endpoint = "http://localhost:3000"

features = [
    "connection.manual",
    #"simple"
    #"basicmessage.manual",
    #"trustping.manual"
]

[config.subject]
endpoint="http://localhost:3001"
